### PR TITLE
Add firebase

### PR DESCRIPTION
**Pull request by rogeriochaves**
This references to issue #8 

This PR pulls data of riders from firebase, I did the minimum possible just to work (PR MVP!), so it need improvements and refactorings.

So, I've manually added data to firebase (and as soon as I discover how, I'll give permissions for you to access it too):

And now I'm showing their names on the screen o/

I'm using the firebase javascript library, but this is temporary, until the lib for elm gets upgraded to elm 0.17, which we are using (the author is working on that):
https://github.com/ThomasWeiser/elmfire

For me this makes it easier for @luismizutani to insert data for riders (instead of changing html directly) before we develop a form

### CODE REVIEW

**Comment by luismizutani** [comment]
Hi Rogerio, Awesome work!

The historic of "caronas" asked by people are today stores in several Google spreadsheets. When we have this part of DB ready, perhaps we can export into a format you can easily populate the tables. I will grant you access to those files too.

Regards

Enviada do meu iPhone

**Comment by rogeriochaves** [comment]
@luismizutani okay but... do we really need this history?

**Comment by luismizutani** [comment]
Not sure. Perhaps we do not need. What do you suggest?

Enviada do meu iPhone

**Comment by rogeriochaves** [comment]
Since this doesn't break the current version, I'll merge so we can keep moving, if we change our mind I revert it

**Pull request merged**
